package(default_visibility = ["//visibility:public"])

filegroup(
    name = "workspace_files",
    srcs = [
        ".bazelversion",
        ".bazelrc",
        "CHANGELOG.md",
        "Cargo.lock",
        "Cargo.toml",
        "LICENSE",
        "MODULE.bazel",
        "NOTICE",
        "README.md",
    ],
)

filegroup(
    name = "docs",
    srcs = glob([
        "docs/**/*.md",
    ]),
)
