package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob(["src/**/*.rs"]) + [
        "Cargo.toml",
        "pyproject.toml",
    ],
)

genrule(
    name = "material_color_py_extension",
    srcs = [
        "//:Cargo.lock",
        "//:Cargo.toml",
        "//crates/material_color:srcs",
        "//crates/material_color_capi:srcs",
        ":srcs",
    ],
    outs = ["material_color_py.so"],
    cmd = "export CARGO_HOME=\"$${CARGO_HOME:-$${HOME}/.cargo}\"; export PATH=\"$${CARGO_HOME}/bin:$${PATH}\"; CARGO_TARGET_DIR=$(@D)/cargo-target cargo build --offline --locked --manifest-path $(location //:Cargo.toml) --package material_color_py --release && cp $(@D)/cargo-target/release/libmaterial_color_py.so $@",
)
