[package]
name = "material_color_py"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "material_color_py"
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]

[dependencies]
material_color = { path = "../material_color" }
pyo3 = { version = "0.28.3", features = ["abi3-py310"] }

[lints.rust]
unsafe_code = "allow"

[lints.clippy]
all = "warn"
pedantic = "warn"
