#[derive(Clone, Copy, Debug, Eq, PartialEq, Hash)]
pub enum DynamicColorRole {
    PrimaryPaletteKeyColor,
    SecondaryPaletteKeyColor,
    TertiaryPaletteKeyColor,
    NeutralPaletteKeyColor,
    NeutralVariantPaletteKeyColor,
    Background,
    OnBackground,
    Surface,
    SurfaceDim,
    SurfaceBright,
    SurfaceContainerLowest,
    SurfaceContainerLow,
    SurfaceContainer,
    SurfaceContainerHigh,
    SurfaceContainerHighest,
    OnSurface,
    SurfaceVariant,
    OnSurfaceVariant,
    InverseSurface,
    InverseOnSurface,
    Outline,
    OutlineVariant,
    Shadow,
    Scrim,
    SurfaceTint,
    Primary,
    OnPrimary,
    PrimaryContainer,
    OnPrimaryContainer,
    InversePrimary,
    Secondary,
    OnSecondary,
    SecondaryContainer,
    OnSecondaryContainer,
    Tertiary,
    OnTertiary,
    TertiaryContainer,
    OnTertiaryContainer,
    Error,
    OnError,
    ErrorContainer,
    OnErrorContainer,
    PrimaryFixed,
    PrimaryFixedDim,
    OnPrimaryFixed,
    OnPrimaryFixedVariant,
    SecondaryFixed,
    SecondaryFixedDim,
    OnSecondaryFixed,
    OnSecondaryFixedVariant,
    TertiaryFixed,
    TertiaryFixedDim,
    OnTertiaryFixed,
    OnTertiaryFixedVariant,
}

impl DynamicColorRole {
    pub const ALL: [Self; 54] = [
        Self::PrimaryPaletteKeyColor,
        Self::SecondaryPaletteKeyColor,
        Self::TertiaryPaletteKeyColor,
        Self::NeutralPaletteKeyColor,
        Self::NeutralVariantPaletteKeyColor,
        Self::Background,
        Self::OnBackground,
        Self::Surface,
        Self::SurfaceDim,
        Self::SurfaceBright,
        Self::SurfaceContainerLowest,
        Self::SurfaceContainerLow,
        Self::SurfaceContainer,
        Self::SurfaceContainerHigh,
        Self::SurfaceContainerHighest,
        Self::OnSurface,
        Self::SurfaceVariant,
        Self::OnSurfaceVariant,
        Self::InverseSurface,
        Self::InverseOnSurface,
        Self::Outline,
        Self::OutlineVariant,
        Self::Shadow,
        Self::Scrim,
        Self::SurfaceTint,
        Self::Primary,
        Self::OnPrimary,
        Self::PrimaryContainer,
        Self::OnPrimaryContainer,
        Self::InversePrimary,
        Self::Secondary,
        Self::OnSecondary,
        Self::SecondaryContainer,
        Self::OnSecondaryContainer,
        Self::Tertiary,
        Self::OnTertiary,
        Self::TertiaryContainer,
        Self::OnTertiaryContainer,
        Self::Error,
        Self::OnError,
        Self::ErrorContainer,
        Self::OnErrorContainer,
        Self::PrimaryFixed,
        Self::PrimaryFixedDim,
        Self::OnPrimaryFixed,
        Self::OnPrimaryFixedVariant,
        Self::SecondaryFixed,
        Self::SecondaryFixedDim,
        Self::OnSecondaryFixed,
        Self::OnSecondaryFixedVariant,
        Self::TertiaryFixed,
        Self::TertiaryFixedDim,
        Self::OnTertiaryFixed,
        Self::OnTertiaryFixedVariant,
    ];

    #[must_use]
    pub const fn name(self) -> &'static str {
        match self {
            Self::PrimaryPaletteKeyColor => "primary_palette_key_color",
            Self::SecondaryPaletteKeyColor => "secondary_palette_key_color",
            Self::TertiaryPaletteKeyColor => "tertiary_palette_key_color",
            Self::NeutralPaletteKeyColor => "neutral_palette_key_color",
            Self::NeutralVariantPaletteKeyColor => "neutral_variant_palette_key_color",
            Self::Background => "background",
            Self::OnBackground => "on_background",
            Self::Surface => "surface",
            Self::SurfaceDim => "surface_dim",
            Self::SurfaceBright => "surface_bright",
            Self::SurfaceContainerLowest => "surface_container_lowest",
            Self::SurfaceContainerLow => "surface_container_low",
            Self::SurfaceContainer => "surface_container",
            Self::SurfaceContainerHigh => "surface_container_high",
            Self::SurfaceContainerHighest => "surface_container_highest",
            Self::OnSurface => "on_surface",
            Self::SurfaceVariant => "surface_variant",
            Self::OnSurfaceVariant => "on_surface_variant",
            Self::InverseSurface => "inverse_surface",
            Self::InverseOnSurface => "inverse_on_surface",
            Self::Outline => "outline",
            Self::OutlineVariant => "outline_variant",
            Self::Shadow => "shadow",
            Self::Scrim => "scrim",
            Self::SurfaceTint => "surface_tint",
            Self::Primary => "primary",
            Self::OnPrimary => "on_primary",
            Self::PrimaryContainer => "primary_container",
            Self::OnPrimaryContainer => "on_primary_container",
            Self::InversePrimary => "inverse_primary",
            Self::Secondary => "secondary",
            Self::OnSecondary => "on_secondary",
            Self::SecondaryContainer => "secondary_container",
            Self::OnSecondaryContainer => "on_secondary_container",
            Self::Tertiary => "tertiary",
            Self::OnTertiary => "on_tertiary",
            Self::TertiaryContainer => "tertiary_container",
            Self::OnTertiaryContainer => "on_tertiary_container",
            Self::Error => "error",
            Self::OnError => "on_error",
            Self::ErrorContainer => "error_container",
            Self::OnErrorContainer => "on_error_container",
            Self::PrimaryFixed => "primary_fixed",
            Self::PrimaryFixedDim => "primary_fixed_dim",
            Self::OnPrimaryFixed => "on_primary_fixed",
            Self::OnPrimaryFixedVariant => "on_primary_fixed_variant",
            Self::SecondaryFixed => "secondary_fixed",
            Self::SecondaryFixedDim => "secondary_fixed_dim",
            Self::OnSecondaryFixed => "on_secondary_fixed",
            Self::OnSecondaryFixedVariant => "on_secondary_fixed_variant",
            Self::TertiaryFixed => "tertiary_fixed",
            Self::TertiaryFixedDim => "tertiary_fixed_dim",
            Self::OnTertiaryFixed => "on_tertiary_fixed",
            Self::OnTertiaryFixedVariant => "on_tertiary_fixed_variant",
        }
    }
}
