load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "headers",
    srcs = glob(["include/**/*.h"]),
)

cc_library(
    name = "material_color_c",
    hdrs = glob(["include/**/*.h"]),
    includes = ["include"],
    deps = ["//crates/material_color_capi:material_color_capi_static"],
)
