load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(default_visibility = ["//visibility:public"])

filegroup(
    name = "srcs",
    srcs = glob([
        "include/**/*.hpp",
        "src/**/*.cpp",
    ]),
)

cc_library(
    name = "material_color_cpp",
    srcs = glob(["src/**/*.cpp"]),
    hdrs = glob(["include/**/*.hpp"]),
    includes = ["include"],
    deps = ["//bindings/c:material_color_c"],
)
