pub mod content;
pub mod expressive;
pub mod fidelity;
pub mod fruit_salad;
pub mod monochrome;
pub mod neutral;
pub mod rainbow;
pub mod tonal_spot;
pub mod vibrant;

pub use content::scheme_content;
pub use expressive::scheme_expressive;
pub use fidelity::scheme_fidelity;
pub use fruit_salad::scheme_fruit_salad;
pub use monochrome::scheme_monochrome;
pub use neutral::scheme_neutral;
pub use rainbow::scheme_rainbow;
pub use tonal_spot::scheme_tonal_spot;
pub use vibrant::scheme_vibrant;
